### ISSUE TITLE
"Power Your Creativity With Artificial Intelligence" Learn More does not show detail page

### ISSUE THREAD

**Issue by kmlhsn** [front-end-by-rimantas/19-grupe-portfolio-neuron#158]
1. Go to http://demo.auburnforest.com/html/neuron/demo/index.html
2. Scroll Down to "Power Your Creativity With Artificial Intelligence"

"Learn More" Button does not redirect to detail page.
![image](https://user-images.githubusercontent.com/32615215/103177230-bdbb4280-48a2-11eb-92cc-349966d2124f.png)

**Comment by belauzas** [comment]
Please stop guessing what should be implemented 🐹 If something is not implemented, it doesn't mean it's a bug.
